version: '3.8'

services:
  # Service PHP
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projet_actual_php
    volumes:
      - ./:/var/www/html
    networks:
      - actual_network
    depends_on:
      - mysql

  # Service MySQL
  mysql:
    image: mysql:8.0
    container_name: projet_actual_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: actual_db
      MYSQL_USER: actual_user
      MYSQL_PASSWORD: actual_pass
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - actual_network

  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: projet_actual_nginx
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - actual_network
    depends_on:
      - php

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  mysql_data:

networks:
  actual_network:
    driver: bridge
